
import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  ChevronLeft, 
  ChevronRight, 
  Hourglass, 
  Sparkles, 
  Award, 
  Feather, 
  Download, 
  X 
} from 'lucide-react';
import { format } from 'date-fns';
import { QRCodeSVG } from 'qrcode.react';
import { Certificate } from '../types';

interface CertificateModalProps {
  isOpen: boolean;
  onClose: () => void;
  allCertificates: Certificate[];
  currentCertificateIndex: number;
  setCurrentCertificateIndex: React.Dispatch<React.SetStateAction<number>>;
  isMobile: boolean;
  isDownloading: boolean;
  handleDownloadCertificate: () => void;
  onboardingName: string;
  setOnboardingName: React.Dispatch<React.SetStateAction<string>>;
  isEditingCertificateName: boolean;
  setIsEditingCertificateName: React.Dispatch<React.SetStateAction<boolean>>;
  updateUserName: (name: string) => void;
  autoGeneratedCertImage: string | null;
  isAutoGenerating: boolean;
  certificateRef: React.RefObject<HTMLDivElement>;
}

export const CertificateModal: React.FC<CertificateModalProps> = ({
  isOpen,
  onClose,
  allCertificates,
  currentCertificateIndex,
  setCurrentCertificateIndex,
  isMobile,
  isDownloading,
  handleDownloadCertificate,
  onboardingName,
  setOnboardingName,
  isEditingCertificateName,
  setIsEditingCertificateName,
  updateUserName,
  autoGeneratedCertImage,
  isAutoGenerating,
  certificateRef,
}) => {
  if (!allCertificates[currentCertificateIndex]) return null;

  return (
    <AnimatePresence mode="wait">
      {isOpen && allCertificates.length > 0 && (
        <div className="fixed inset-0 z-[60] flex items-center justify-center p-4 overflow-hidden">
          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="absolute inset-0 bg-white/40 backdrop-blur-xl"
          />

          <div className="relative z-10 w-full max-w-lg flex flex-col items-center">
            {allCertificates[currentCertificateIndex] && (
              <>
                {/* Navigation Arrows (Desktop) */}
                {!isMobile && allCertificates.length > 1 && (
                  <>
                    <button 
                      onClick={(e) => {
                        e.stopPropagation();
                        setCurrentCertificateIndex(prev => (prev > 0 ? prev - 1 : allCertificates.length - 1));
                      }}
                      className="absolute -left-16 top-1/2 -translate-y-1/2 w-12 h-12 rounded-full bg-white/80 backdrop-blur-md border border-stone-200 flex items-center justify-center text-stone-600 hover:bg-white transition-all shadow-lg z-20"
                    >
                      <ChevronLeft size={24} />
                    </button>
                    <button 
                      onClick={(e) => {
                        e.stopPropagation();
                        setCurrentCertificateIndex(prev => (prev < allCertificates.length - 1 ? prev + 1 : 0));
                      }}
                      className="absolute -right-16 top-1/2 -translate-y-1/2 w-12 h-12 rounded-full bg-white/80 backdrop-blur-md border border-stone-200 flex items-center justify-center text-stone-600 hover:bg-white transition-all shadow-lg z-20"
                    >
                      <ChevronRight size={24} />
                    </button>
                  </>
                )}

                <AnimatePresence mode="wait">
                  <motion.div 
                    key={allCertificates[currentCertificateIndex].id}
                    initial={{ opacity: 0, x: 20, scale: 0.95 }}
                    animate={{ opacity: 1, x: 0, scale: 1 }}
                    exit={{ opacity: 0, x: -20, scale: 0.95 }}
                    transition={{ duration: 0.4, ease: "easeOut" }}
                    drag="x"
                    dragConstraints={{ left: 0, right: 0 }}
                    onDragEnd={(_, info) => {
                      if (info.offset.x > 100) {
                        setCurrentCertificateIndex(prev => (prev > 0 ? prev - 1 : allCertificates.length - 1));
                      } else if (info.offset.x < -100) {
                        setCurrentCertificateIndex(prev => (prev < allCertificates.length - 1 ? prev + 1 : 0));
                      }
                    }}
                    className="w-full flex justify-center"
                  >
                    <div className="w-full flex justify-center relative">
                      {/* The Certificate Card (HTML version, hidden once image is ready) */}
                      <div 
                        ref={certificateRef}
                        className={`
                        p-2 md:p-3 rounded-sm shadow-2xl border-[8px] md:border-[12px] relative overflow-hidden transition-all duration-1000
                        w-[300px] sm:w-[340px] md:w-[480px] mx-auto box-border
                        ${allCertificates[currentCertificateIndex].isCenturyTraveler 
                          ? 'bg-[#020617] border-[#1e293b]' 
                          : 'bg-[#F5F2ED] border-white'
                        }
                        ${autoGeneratedCertImage ? 'opacity-0 pointer-events-none' : 'opacity-100'}
                      `}>
                        {/* Inner Border/Glow for Century Traveler */}
                        {allCertificates[currentCertificateIndex].isCenturyTraveler && (
                          <div className="absolute inset-[6px] md:inset-[8px] border border-[rgba(96,165,250,0.2)] pointer-events-none z-10" />
                        )}
                        {/* Decorative Inner Border */}
                        <div className={`
                          border pt-[62px] pb-[46px] px-4 md:pt-[88px] md:pb-[68px] md:px-6 flex flex-col items-center text-center relative transition-colors duration-1000 w-full h-full box-border
                          ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'border-[rgba(59,130,246,0.2)]' : 'border-stone-300'}
                        `}>
                            {/* Background Watermark */}
                            <div className={`
                              absolute inset-0 flex items-center justify-center pointer-events-none transition-opacity duration-1000
                              ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'opacity-[0.07] text-[#93c5fd]' : 'opacity-[0.03] text-[#292524]'}
                            `}>
                              <Hourglass size={240} className="md:w-[340px] md:h-[340px]" />
                            </div>

                            {/* Century Traveler Special Effects */}
                            {allCertificates[currentCertificateIndex].isCenturyTraveler && (
                              <>
                                <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-b from-blue-900/20 to-transparent pointer-events-none" />
                                <div className="absolute top-[6px] left-[6px] w-8 h-8 border-t border-l border-blue-400/30 rounded-tl-sm pointer-events-none z-30" />
                                <div className="absolute top-[6px] right-[6px] w-8 h-8 border-t border-r border-blue-400/30 rounded-tr-sm pointer-events-none z-30" />
                                <div className="absolute bottom-[6px] left-[6px] w-8 h-8 border-b border-l border-blue-400/30 rounded-bl-sm pointer-events-none z-30" />
                                <div className="absolute bottom-[6px] right-[6px] w-8 h-8 border-b border-r border-blue-400/30 rounded-br-sm pointer-events-none z-30" />

                                <div className="absolute top-3 left-1/2 -translate-x-1/2 md:top-6 w-full flex justify-center">
                                  <motion.div 
                                    initial={{ opacity: 0, scale: 0.5 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    className="bg-gradient-to-r from-[rgba(37,99,235,0.2)] to-[rgba(79,70,229,0.2)] border border-[rgba(96,165,250,0.4)] px-2 py-0.5 md:px-3 md:py-1 rounded-full flex items-center gap-1 md:gap-1.5 shadow-[0_0_15px_rgba(59,130,246,0.2)] whitespace-nowrap"
                                  >
                                    <Sparkles size={12} className="text-[#93c5fd] shrink-0" />
                                    <span className="text-[8px] md:text-[10px] font-bold text-[#bfdbfe] uppercase tracking-[0.2em] whitespace-nowrap">22 世纪见证者</span>
                                  </motion.div>
                                </div>
                              </>
                            )}

                            {/* Header */}
                            <div className="mb-2 md:mb-8 w-full overflow-hidden">
                              <div className={`flex justify-center mb-1 md:mb-4 transition-colors duration-1000 ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[#60a5fa]' : 'text-[#292524]'}`}>
                                <Award size={isMobile ? 32 : 44} className="md:w-11 md:h-11" strokeWidth={1} />
                              </div>
                              <h2 className={`
                                text-[11px] sm:text-sm md:text-xl lg:text-2xl font-serif font-light tracking-[0.1em] md:tracking-[0.2em] uppercase mb-1 md:mb-2 transition-colors duration-1000 w-full mx-auto leading-tight max-w-none
                                ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[#eff6ff] drop-shadow-[0_0_8px_rgba(59,130,246,0.5)]' : 'text-[#292524]'}
                              `}>
                                {allCertificates[currentCertificateIndex].isCenturyTraveler ? '世纪旅者 · 时光守护者证书' : '时光守护者证书'}
                              </h2>
                              <div className={`h-[1px] w-20 md:w-24 mx-auto mb-1 transition-colors duration-1000 ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'bg-[rgba(59,130,246,0.5)]' : 'bg-[#a8a29e]'}`}></div>
                              <p className={`
                                text-[8px] md:text-[10px] tracking-[0.3em] uppercase font-bold transition-colors duration-1000
                                ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[rgba(96,165,250,0.7)]' : 'text-[#78716c]'}
                              `}>
                                {allCertificates[currentCertificateIndex].isCenturyTraveler ? 'Century Traveler Certificate' : 'Time Guardian Certificate'}
                              </p>
                            </div>

                            {/* Content */}
                            <div className="space-y-3 md:space-y-4 mb-4 md:mb-8 relative z-10">
                              <div>
                                {isEditingCertificateName ? (
                                  <div className="flex flex-col items-center gap-2">
                                    <input 
                                      autoFocus
                                      type="text"
                                      className={`
                                        text-base md:text-2xl font-bold border-b outline-none text-center px-2 py-1 w-36 md:w-48 transition-all
                                        ${allCertificates[currentCertificateIndex].isCenturyTraveler 
                                          ? 'text-white bg-[rgba(30,58,138,0.2)] border-[rgba(59,130,246,0.5)]' 
                                          : 'text-stone-800 bg-white/50 border-stone-400'
                                        }
                                      `}
                                      value={onboardingName}
                                      onChange={(e) => setOnboardingName(e.target.value)}
                                      onBlur={() => {
                                        if (onboardingName.trim() && onboardingName !== allCertificates[currentCertificateIndex].sender) {
                                          updateUserName(onboardingName);
                                        } else {
                                          setIsEditingCertificateName(false);
                                        }
                                      }}
                                      onKeyDown={(e) => {
                                        if (e.key === 'Enter') {
                                          updateUserName(onboardingName);
                                        }
                                      }}
                                    />
                                    <p className="text-[8px] md:text-[9px] text-stone-400 uppercase tracking-widest font-bold">按回车键确认</p>
                                  </div>
                                ) : (
                                  <div 
                                    className="group cursor-pointer relative inline-block"
                                    onClick={() => {
                                      setOnboardingName(allCertificates[currentCertificateIndex].sender);
                                      setIsEditingCertificateName(true);
                                    }}
                                  >
                                    <h3 className={`
                                      text-base md:text-2xl font-bold mb-1 transition-colors duration-1000 whitespace-nowrap tracking-tight md:tracking-normal
                                      ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[#dbeafe]' : 'text-[#292524]'}
                                    `}>
                                      {allCertificates[currentCertificateIndex].sender}
                                    </h3>
                                    <div className="absolute -right-5 top-1/2 -translate-y-1/2 opacity-40 md:opacity-0 md:group-hover:opacity-100 transition-opacity">
                                      <Feather size={14} className={allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[#60a5fa]' : 'text-[#a8a29e]'} />
                                    </div>
                                    <div className={`h-[1px] w-24 md:w-32 mx-auto transition-colors duration-1000 ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'bg-[rgba(59,130,246,0.3)]' : 'bg-[#d6d3d1]'}`}></div>
                                  </div>
                                )}
                              </div>

                              <p className={`leading-relaxed max-w-none mx-auto text-xs md:text-sm transition-colors duration-1000 ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[rgba(219,234,254,0.8)]' : 'text-[#57534e]'}`}>
                                在 <span className={`font-bold ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[#60a5fa]' : 'text-[#1c1917]'}`}>{allCertificates[currentCertificateIndex].departureYear}</span> 年寄出了一份跨越时空的承诺。
                                {allCertificates[currentCertificateIndex].isCenturyTraveler ? (
                                  <>此胶囊已进入 <span className="text-[#60a5fa] font-bold">世纪航线</span>，将于 <span className="text-[#60a5fa] font-bold">{allCertificates[currentCertificateIndex].arrivalYear}</span> 年准时开启。</>
                                ) : (
                                  <>此胶囊已进入永恒轨道，将于 <span className="text-[#1c1917] font-bold">{allCertificates[currentCertificateIndex].arrivalYear}</span> 年准时开启。</>
                                )}
                              </p>

                              <p className={`italic text-[10px] md:text-xs transition-colors duration-1000 ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[rgba(96,165,250,0.6)]' : 'text-[#78716c]'}`}>
                                {allCertificates[currentCertificateIndex].isCenturyTraveler ? '“跨越世纪的曙光，只为遇见未来的你。”' : '“时光流转，承诺的温度永恒。”'}
                              </p>
                            </div>

                            {/* Footer / Seal & QR Code */}
                            <div className="w-full relative flex justify-between items-center mt-1 md:mt-2 min-h-[60px] md:min-h-[90px]">
                              <div className="text-left relative flex items-center">
                                <div className={`
                                  p-1 rounded-lg bg-white shadow-sm transition-all duration-1000
                                  ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'border border-blue-400/30' : ''}
                                `}>
                                  <QRCodeSVG 
                                    value={window.location.href} 
                                    size={isMobile ? 44 : 64}
                                    level="M"
                                    includeMargin={true}
                                    marginSize={1}
                                    fgColor={allCertificates[currentCertificateIndex].isCenturyTraveler ? "#0F172A" : "#2D2A26"}
                                  />
                                </div>
                              </div>

                              <div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 group/seal">
                                <div className="w-12 h-12 md:w-20 md:h-20 relative">
                                  {/* Outer irregular shape with shadow */}
                                  <div className={`
                                    absolute inset-0 rounded-[45%_55%_50%_50%/50%_45%_55%_50%] shadow-lg transition-colors duration-1000
                                    ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'bg-[#2E1065]' : 'bg-[#8B1A1A]'}
                                  `}></div>
                                  
                                  {/* Inner 3D effect layers */}
                                  <div className={`
                                    absolute inset-0 rounded-[45%_55%_50%_50%/50%_45%_55%_50%] opacity-50
                                    ${allCertificates[currentCertificateIndex].isCenturyTraveler 
                                      ? 'bg-gradient-to-br from-white/20 to-black/40' 
                                      : 'bg-gradient-to-br from-white/20 to-black/40'}
                                  `}></div>

                                  <div className={`
                                    absolute inset-[10%] rounded-full flex items-center justify-center overflow-hidden border transition-colors duration-1000 shadow-inner
                                    ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'bg-[#4C1D95] border-violet-400/30' : 'bg-[#991B1B] border-red-900/30'}
                                  `}>
                                    <svg viewBox="0 0 100 100" className="w-[85%] h-[85%]">
                                      <defs>
                                        <linearGradient id="goldGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                                          <stop offset="0%" stopColor="#D4AF37" />
                                          <stop offset="50%" stopColor="#FFD700" />
                                          <stop offset="100%" stopColor="#AA8A2E" />
                                        </linearGradient>
                                      </defs>
                                      <g fill="none" stroke="url(#goldGradient)">
                                        <circle cx="50" cy="50" r="42" strokeWidth="0.5" opacity="0.6" />
                                        <path d="M50 8 A42 42 0 0 1 92 50" strokeWidth="1.2" strokeLinecap="round" />
                                        <circle cx="50" cy="50" r="34" strokeWidth="0.8" />
                                        <circle cx="50" cy="50" r="26" strokeWidth="1" />
                                        <circle cx="50" cy="50" r="18" strokeWidth="1.2" />
                                        <path d="M50 50 L50 25" strokeWidth="2.5" strokeLinecap="round" />
                                        <path d="M50 50 L70 50" strokeWidth="2" strokeLinecap="round" />
                                        <circle cx="50" cy="50" r="3" fill="url(#goldGradient)" stroke="none" />
                                        <path d="M75 25 Q80 20 85 25 T75 35 Z" fill="url(#goldGradient)" stroke="none" transform="rotate(15 75 25)" />
                                        <path d="M25 70 Q20 75 25 80 T35 70 Z" fill="url(#goldGradient)" stroke="none" transform="rotate(-20 25 70)" />
                                        <path d="M40 15 Q45 12 50 15" strokeWidth="0.3" opacity="0.5" />
                                        <path d="M60 85 Q55 88 50 85" strokeWidth="0.3" opacity="0.5" />
                                      </g>
                                    </svg>
                                    <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/natural-paper.png')] opacity-20 mix-blend-overlay pointer-events-none"></div>
                                  </div>
                                  <div className="absolute top-[10%] left-[10%] w-[40%] h-[40%] bg-gradient-to-br from-[rgba(255,255,255,0.2)] to-transparent rounded-full blur-lg pointer-events-none"></div>
                                </div>
                                <p className={`absolute -bottom-5 md:bottom-[-22px] left-1/2 -translate-x-1/2 whitespace-nowrap text-[8px] md:text-[10px] font-bold tracking-[0.2em] uppercase transition-colors duration-1000 ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[rgba(96,165,250,0.7)]' : 'text-[#a8a29e]'}`}>
                                  时光邮局 · 岁轮
                                </p>
                              </div>

                              <div className="text-right flex flex-col gap-3 md:gap-4 min-w-[120px]">
                                <div>
                                  <p className="text-[8px] md:text-[9px] text-[#a8a29e] uppercase tracking-widest font-bold mb-0.5 md:mb-1 whitespace-nowrap">证书编号</p>
                                  <p className={`text-[10px] md:text-xs font-mono transition-colors duration-1000 whitespace-nowrap ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[rgba(147,197,253,0.7)]' : 'text-[#57534e]'}`}>{allCertificates[currentCertificateIndex].id}</p>
                                </div>
                                <div>
                                  <p className="text-[8px] md:text-[9px] text-[#a8a29e] uppercase tracking-widest font-bold mb-0.5 md:mb-1 whitespace-nowrap">签发日期</p>
                                  <p className={`text-[10px] md:text-xs font-medium italic transition-colors duration-1000 whitespace-nowrap ${allCertificates[currentCertificateIndex].isCenturyTraveler ? 'text-[rgba(147,197,253,0.7)]' : 'text-[#57534e]'}`}>{format(allCertificates[currentCertificateIndex].date, 'yyyy.MM.dd')}</p>
                                </div>
                              </div>
                            </div>
                        </div>
                      </div>

                      {/* Static Image Version */}
                      {autoGeneratedCertImage && (
                        <div className="absolute inset-0 flex justify-center items-center z-50">
                          <img 
                            src={autoGeneratedCertImage} 
                            alt="证书" 
                            className="w-[300px] sm:w-[340px] md:w-[480px] shadow-2xl rounded-sm border-[8px] md:border-[12px] border-transparent"
                            style={{ pointerEvents: 'auto' }}
                          />
                        </div>
                      )}

                      {/* Loading State */}
                      {isAutoGenerating && (
                        <div className="absolute inset-0 flex items-center justify-center bg-white/5 backdrop-blur-[1px] z-40 rounded-sm">
                          <div className="flex flex-col items-center gap-3">
                            <div className="w-10 h-10 border-4 border-blue-500/20 border-t-blue-500 rounded-full animate-spin" />
                            <p className="text-[10px] text-blue-500 font-bold uppercase tracking-widest">正在生成高清图像...</p>
                          </div>
                        </div>
                      )}
                    </div>
                  </motion.div>
                </AnimatePresence>

                {/* Pagination Indicator */}
                {allCertificates.length > 1 && (
                  <div className="mt-6 flex items-center gap-2 bg-[rgba(255,255,255,0.5)] backdrop-blur-md px-4 py-1.5 rounded-full border border-[rgba(231,229,228,0.5)] shadow-sm">
                    {allCertificates.map((_, idx) => (
                      <button
                        key={idx}
                        onClick={() => setCurrentCertificateIndex(idx)}
                        className={`w-1.5 h-1.5 rounded-full transition-all duration-300 ${idx === currentCertificateIndex ? 'bg-[#292524] w-4' : 'bg-[#d6d3d1] hover:bg-[#a8a29e]'}`}
                      />
                    ))}
                  </div>
                )}

                {/* Action Buttons */}
                <div className="mt-6 md:mt-8 flex justify-center gap-4">
                  <button 
                    onClick={onClose}
                    className="px-8 py-3 bg-[rgba(245,245,244,0.8)] hover:bg-[rgba(231,229,228,0.8)] backdrop-blur-md text-stone-500 rounded-full text-sm font-bold transition-all border border-[rgba(231,229,228,0.5)] flex items-center gap-2"
                  >
                    <X size={16} />
                    关闭
                  </button>
                  <button 
                    onClick={handleDownloadCertificate}
                    disabled={isDownloading}
                    className="px-8 py-3 bg-stone-900 hover:bg-stone-800 text-white rounded-full text-sm font-bold transition-all shadow-xl flex items-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
                  >
                    {isDownloading ? (
                      <div className="w-4 h-4 border-2 border-[rgba(255,255,255,0.2)] border-t-white rounded-full animate-spin"></div>
                    ) : (
                      <Download size={16} />
                    )}
                    <span className="whitespace-nowrap">
                      {isDownloading ? '保存中...' : '保存证书'}
                    </span>
                  </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}
    </AnimatePresence>
  );
};
